# Generated by Django 4.2.3 on 2023-08-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_remove_payment_payment_method_remove_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
